// Auto-generated by @navai/playground-web (generate-web-module-loaders.mjs)
import type { NavaiFunctionModuleLoaders } from "@navai/voice-frontend";

export const NAVAI_WEB_MODULE_LOADERS: NavaiFunctionModuleLoaders = {
  "src/ai/functions-modules/session/logout.fn.ts": async () => await import("./functions-modules/session/logout.fn"),
  "src/ai/functions-modules/support/open-help.fn.ts": async () => await import("./functions-modules/support/open-help.fn"),
  "src/ai/functions-modules/system/ai-service.ts": async () => await import("./functions-modules/system/ai-service"),
  "src/ai/functions-modules/test/testing.ts": async () => await import("./functions-modules/test/testing"),
  "src/ai/functions-modules/utils/math.ts": async () => await import("./functions-modules/utils/math")
};
