// Auto-generated by @navai/voice-mobile (navai-generate-mobile-loaders)
import type { NavaiFunctionModuleLoaders } from "@navai/voice-mobile";

export const NAVAI_MOBILE_MODULE_LOADERS: NavaiFunctionModuleLoaders = {
  "src/ai/functions-modules/session/logout.fn.ts": async () => await import("./functions-modules/session/logout.fn"),
  "src/ai/functions-modules/support/open-help.fn.ts": async () => await import("./functions-modules/support/open-help.fn"),
  "src/ai/functions-modules/system/ai-service.ts": async () => await import("./functions-modules/system/ai-service"),
  "src/ai/functions-modules/test/testing.ts": async () => await import("./functions-modules/test/testing"),
  "src/ai/functions-modules/utils/math.ts": async () => await import("./functions-modules/utils/math"),
  "src/ai/routes.ts": async () => await import("./routes"),
  "src/pages/ActivityScreen.tsx": async () => await import("../pages/ActivityScreen"),
  "src/pages/BillingScreen.tsx": async () => await import("../pages/BillingScreen"),
  "src/pages/HelpScreen.tsx": async () => await import("../pages/HelpScreen"),
  "src/pages/HomeScreen.tsx": async () => await import("../pages/HomeScreen"),
  "src/pages/ProfileScreen.tsx": async () => await import("../pages/ProfileScreen"),
  "src/pages/SettingsScreen.tsx": async () => await import("../pages/SettingsScreen")
};
